### ISSUE TITLE
Rossby Wave Source formula

### ISSUE THREAD

**Issue by didiermonselesan** [ajdawson/windspharm#53]
Is the Rossby Wave source formula correct in rws_example.py?
S = -eta * div - uchi * etax - vchi * etay  and not S = -eta * div - uchi * etax + vchi * etay as per example
S = -eta * div - dot(v_chi , grad(eta))
Cheers, Didier

**Comment by ajdawson** [comment]
This is already fixed on the master branch, but not in the 1.3 release branch. This needs to be back-ported and new documentation published.

**Comment by ajdawson** [comment]
Fixed in on-line documentation after cherry-picking 3a7f0f5461f6a50aa0827ed752845ccfcb0795f9, c6f5657593478fdf4a2567f9cf90997333ac6204 and fce0877590bc9df41157827d539d9dd1a5c67c6d from the master branch and doing a custom documentation build.

No new release has been created to fix this in the release code, this could be done as a further action.
